### ISSUE TITLE
Socket Client Multithreading Problem

### ISSUE THREAD

**Issue by AsadShahi** [Diamond-Family/Chat_Room#14]
import socket

ClientSocket = socket.socket()
host = '127.0.0.1'
port = 1233

print('Waiting for connection')
try:
    ClientSocket.connect((host, port))
except socket.error as e:
    print(str(e))

Response = ClientSocket.recv(1024)
while True:
    Input = input('Say Something: ')
    ClientSocket.send(str.encode(Input))
    Response = ClientSocket.recv(1024)
    print(Response.decode('utf-8'))

ClientSocket.close()

I used this codes for creating thread using while loop but It did not work.

**Comment by AsadShahi** [comment]
I used this codes for creating thread using while loop but It did not work.

**Comment by HamdullahHamdard** [comment]
First initialize everything like class , variable and exiption handling lib 

the sever ip  and port no and the Client IP  and port no will BE same

then create your Server class in another package
Now run server and client

inshallah it will work
