### ISSUE TITLE
Peer2peer not working now!

### ISSUE THREAD

**Issue by HamdullahHamdard** [Diamond-Family/Chat_Room#15]
فیر ټو فیر کنکشن کار نکوی 
نه پوهیږم څه مشکل دی

**Comment by WasiSabir** [comment]
In peer-to-peer (P2P) networking, a group of computers are linked together with equal permissions and responsibilities for processing data. Unlike traditional client-server networking, no devices in a P2P network are designated solely to serve or to receive data.
https://www.webroot.com › glossary
