### ISSUE TITLE
When clients are going to be added, why there names are not displayed on the server console?

### ISSUE THREAD

**Issue by Sabirjankp** [Diamond-Family/Chat_Room#5]

**Comment by HamdullahHamdard** [comment]
کود یی نسم لیکلی 
خو ما دغه نوم چی کلاینټ نوم و سرور ته هم ښکاره سی په کلاینټ هینډلر کلاس کی یو بل واریبل د یوزرنیم په نوم معرفی  کی 
هغه ته می هغه نوم اساین کی کوم چی د کلاینټ څخه کلاینټ هینډلر ته راځی د ساکیټ په واسطه 

بیا می هغه د سرور په کلاس کی د کلاینټ هینډلر په واسطه راواخیستی او فرینټ می کړی 

په دی سره دغه مشکل رفع سو. 
او یو نوی ځانګړتیا مو ور اضافه کړل.
